
  -- create the database tables for Adapt It Service
  CREATE TABLE IF NOT EXISTS projects (
  id INTEGER primary key, 
  projectid TEXT NOT NULL UNIQUE, 
  SourceFont TEXT, 
  SourceFontSize TEXT,
  SourceColor TEXT,
  TargetFont TEXT,
  TargetFontSize TEXT,
  TargetColor TEXT,
  NavigationFont TEXT,
  NavigationFontSize TEXT,
  NavigationColor TEXT,
  SpecialTextColor TEXT,
  RetranslationColor TEXT,
  TextDifferencesColor TEXT,
  SourceLanguageName TEXT,
  SourceLanguageCode TEXT,
  TargetLanguageName TEXT,
  TargetLanguageCode TEXT,
  SourceVariant TEXT,
  TargetVariant TEXT,
  CopyPunctuation TEXT,
  PunctPairs TEXT,
  AutoCapitalization TEXT,
  SourceHasUpperCase TEXT,
  CasePairs TEXT,
  SourceDir TEXT,
  TargetDir TEXT,
  NavDir TEXT,
  name TEXT,
  CustomFilters TEXT,
  FilterMarkers TEXT
);
